name: betterplot_dev
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - sourmash>=4.9.2,<5
    - sourmash_plugin_branchwater>=0.9.13,<1
    - pip
    - pytest
    - matplotlib
    - numpy
    - scipy
    - scikit-learn
    - snakemake-minimal
    - make
    - seaborn
    - plotly
    - biopython
    - ete4>=4.3.0,<5
    - pip:
      - kaleido
