name: betterplot_dev
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - sourmash>=4.8.8,<5
    - sourmash_plugin_branchwater>=0.9.7
    - pip
    - pytest
    - matplotlib
    - numpy
    - scipy
    - scikit-learn
    - snakemake-minimal
    - make
    - seaborn
    - plotly
    - biopython
    - ete3>=3.1.3,<4
    - pip:
      - kaleido
