name: betterplot_dev
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - sourmash>=4.8.8,<5
    - sourmash_plugin_branchwater
    - pip
    - pytest
    - matplotlib
    - numpy
    - scipy
    - scikit-learn
    - snakemake-minimal
    - make
    - seaborn
