sketches_3 = ["2", "47", "63"]
sketches_10 = ["2", "47", "48", "49", "51", "52", "53", "59", "60", "63"]

rule all:
    input:
        "plot2.3sketches.cmp.png",
        "plot2.cut.3sketches.cmp.png",
        "plot2.cut.10sketches.cmp.png",
        "plot2.cut.dendro.10sketches.cmp.png",
        "mds.10sketches.cmp.png",
        "mds2.10sketches.cmp.png",
        "plot2.pairwise.10sketches.cmp.png",
        "plot3.10sketches.cmp.png",
        "clustermap1.10sketches.png",

rule cmp_3sketches:
    input:
        expand("sketches/{n}.sig.zip", n=sketches_3)
    output:
        cmp="3sketches.cmp",
        labels="3sketches.cmp.labels.txt",
        labels_csv="3sketches.cmp.labels_to.csv",
    shell: """
        sourmash compare {input} -o {output.cmp} \
           --labels-to {output.labels_csv}
    """

rule plot2_3sketches:
    input:
        cmp="3sketches.cmp",
        labels="3sketches.cmp.labels_to.csv",
    output:
        "plot2.3sketches.cmp.png",
    shell: """
        sourmash scripts plot2 {input.cmp} {input.labels} -o {output} \
             --figsize-x=5 --figsize-y=3
    """

rule plot2_3sketches_cut:
    input:
        cmp="3sketches.cmp",
        labels="3sketches.cmp.labels_to.csv",
    output:
        "plot2.cut.3sketches.cmp.png",
    shell: """
        sourmash scripts plot2 {input.cmp} {input.labels} -o {output} \
            --cut-point=1.2 --figsize-x=5 --figsize-y=3
    """


rule cmp_10sketches:
    input:
        expand("sketches/{n}.sig.zip", n=sketches_10)
    output:
        cmp="10sketches.cmp",
        labels="10sketches.cmp.labels.txt",
        labels_csv="10sketches.cmp.labels_to.csv",
    shell: """
        sourmash compare {input} -o {output.cmp} \
           --labels-to {output.labels_csv}
    """

rule plot2_10sketches_cut:
    input:
        cmp="10sketches.cmp",
        labels="10sketches.cmp.labels_to.csv",
    output:
        "plot2.cut.10sketches.cmp.png",
    shell: """
        sourmash scripts plot2 {input.cmp} {input.labels} -o {output} \
            --cut-point=1.35 --cluster-out --figsize-x=5 --figsize-y=3
    """

rule plot2_10sketches_cut_dendro_only:
    input:
        cmp="10sketches.cmp",
        labels="10sketches.cmp.labels_to.csv",
    output:
        "plot2.cut.dendro.10sketches.cmp.png",
    shell: """
        sourmash scripts plot2 {input.cmp} {input.labels} -o {output} \
            --cut-point=1.35 --cluster-out --figsize-x=5 --figsize-y=3 \
            --dendrogram-only
    """

rule mds_10sketches:
    input:
        cmp="10sketches.cmp",
        labels="10sketches.cmp.labels_to.csv",
        categories="10sketches-categories.csv",
    output:
        "mds.10sketches.cmp.png"
    shell: """
        sourmash scripts mds {input.cmp} {input.labels} -o {output} \
           -C {input.categories}
    """

rule combine_10sketches:
    input:
        expand("sketches/{n}.sig.zip", n=sketches_10)
    output:
        "10sketches.sig.zip"
    shell: """
        sourmash sig cat {input} -o {output}
    """

rule r10sketches_pairwise:
    input:
        "10sketches.sig.zip",
    output:
        cmp="10sketches.pairwise.csv",
    shell: """
        sourmash scripts pairwise {input} -o {output} --write-all
    """

rule mds2_10sketches:
    input:
        cmp="10sketches.pairwise.csv",
        categories="10sketches-categories.csv",
    output:
        "mds2.10sketches.cmp.png"
    shell: """
        sourmash scripts mds2 {input.cmp} -o {output} \
           -C {input.categories}
    """

rule convert_10sketches_pairwise_to_cmp:
    input:
        cmp="10sketches.pairwise.csv",
    output:
        cmp="10sketches.pairwise.cmp",
        labels_txt="10sketches.pairwise.cmp.labels.txt",
        labels_csv="10sketches.pairwise.cmp.labels_to.csv",
    shell: """
        sourmash scripts pairwise_to_compare {input.cmp} -o {output.cmp} \
            --labels-to {output.labels_csv}
    """
        

rule plot2_10sketches_pairwise:
    input:
        cmp="10sketches.pairwise.cmp",
        labels_csv="10sketches.pairwise.cmp.labels_to.csv",
    output:
        "plot2.pairwise.10sketches.cmp.png",
    shell: """
        sourmash scripts plot2 {input.cmp} {input.labels_csv} -o {output} \
            --figsize-x=5 --figsize-y=3
    """


rule plot3_10sketches:
    input:
        cmp="10sketches.cmp",
        labels="10sketches.cmp.labels_to.csv",
        categories="10sketches-categories.csv",
    output:
        "plot3.10sketches.cmp.png",
    shell: """
        sourmash scripts plot3 {input.cmp} {input.labels} -o {output} \
            -C {input.categories}
    """

rule r10sketches_manysearch:
    input:
        query="10sketches.sig.zip",
        against ="10sketches.sig.zip",
    output:
        cmp="10sketches.manysearch.csv",
    shell: """
        sourmash scripts manysearch {input.query} {input.against} -o {output}
    """

rule clustermap1_10sketches:
    input:
        cmp="10sketches.manysearch.csv",
        categories="10sketches-categories.csv",
    output:
        "clustermap1.10sketches.png",
    shell: """
        sourmash scripts clustermap1 {input.cmp} -o {output} \
            -u containment -R {input.categories} -C {input.categories}
    """
